prop_shared Teo--Amatlan_de_Canas_Dcount.bed Teo--Amatlan_de_Canas_Dcount.bed
prop_shared Teo--Amatlan_de_Canas_Dcount.bed Teo--Crucero_Lagunitas_Dcount.bed
prop_shared Teo--Amatlan_de_Canas_Dcount.bed Teo--El_Rodeo_Dcount.bed
prop_shared Teo--Amatlan_de_Canas_Dcount.bed Teo--Los_Guajes_Dcount.bed
prop_shared Teo--Amatlan_de_Canas_Dcount.bed Teo--San_Lorenzo_Dcount.bed
prop_shared Teo--Amatlan_de_Canas_Dcount.bed Teo--random1_Palmar_Chico_Dcount.bed
prop_shared Teo--Crucero_Lagunitas_Dcount.bed Teo--Amatlan_de_Canas_Dcount.bed
prop_shared Teo--Crucero_Lagunitas_Dcount.bed Teo--Crucero_Lagunitas_Dcount.bed
prop_shared Teo--Crucero_Lagunitas_Dcount.bed Teo--El_Rodeo_Dcount.bed
prop_shared Teo--Crucero_Lagunitas_Dcount.bed Teo--Los_Guajes_Dcount.bed
prop_shared Teo--Crucero_Lagunitas_Dcount.bed Teo--San_Lorenzo_Dcount.bed
prop_shared Teo--Crucero_Lagunitas_Dcount.bed Teo--random1_Palmar_Chico_Dcount.bed
prop_shared Teo--El_Rodeo_Dcount.bed Teo--Amatlan_de_Canas_Dcount.bed
prop_shared Teo--El_Rodeo_Dcount.bed Teo--Crucero_Lagunitas_Dcount.bed
prop_shared Teo--El_Rodeo_Dcount.bed Teo--El_Rodeo_Dcount.bed
prop_shared Teo--El_Rodeo_Dcount.bed Teo--Los_Guajes_Dcount.bed
prop_shared Teo--El_Rodeo_Dcount.bed Teo--San_Lorenzo_Dcount.bed
prop_shared Teo--El_Rodeo_Dcount.bed Teo--random1_Palmar_Chico_Dcount.bed
prop_shared Teo--Los_Guajes_Dcount.bed Teo--Amatlan_de_Canas_Dcount.bed
prop_shared Teo--Los_Guajes_Dcount.bed Teo--Crucero_Lagunitas_Dcount.bed
prop_shared Teo--Los_Guajes_Dcount.bed Teo--El_Rodeo_Dcount.bed
prop_shared Teo--Los_Guajes_Dcount.bed Teo--Los_Guajes_Dcount.bed
prop_shared Teo--Los_Guajes_Dcount.bed Teo--San_Lorenzo_Dcount.bed
prop_shared Teo--Los_Guajes_Dcount.bed Teo--random1_Palmar_Chico_Dcount.bed
prop_shared Teo--San_Lorenzo_Dcount.bed Teo--Amatlan_de_Canas_Dcount.bed
prop_shared Teo--San_Lorenzo_Dcount.bed Teo--Crucero_Lagunitas_Dcount.bed
prop_shared Teo--San_Lorenzo_Dcount.bed Teo--El_Rodeo_Dcount.bed
prop_shared Teo--San_Lorenzo_Dcount.bed Teo--Los_Guajes_Dcount.bed
prop_shared Teo--San_Lorenzo_Dcount.bed Teo--San_Lorenzo_Dcount.bed
prop_shared Teo--San_Lorenzo_Dcount.bed Teo--random1_Palmar_Chico_Dcount.bed
prop_shared Teo--random1_Palmar_Chico_Dcount.bed Teo--Amatlan_de_Canas_Dcount.bed
prop_shared Teo--random1_Palmar_Chico_Dcount.bed Teo--Crucero_Lagunitas_Dcount.bed
prop_shared Teo--random1_Palmar_Chico_Dcount.bed Teo--El_Rodeo_Dcount.bed
prop_shared Teo--random1_Palmar_Chico_Dcount.bed Teo--Los_Guajes_Dcount.bed
prop_shared Teo--random1_Palmar_Chico_Dcount.bed Teo--San_Lorenzo_Dcount.bed
prop_shared Teo--random1_Palmar_Chico_Dcount.bed Teo--random1_Palmar_Chico_Dcount.bed
