#take a with demography info generated by me earlier in the pipeline, build a discoal command 

demography_file = "data/mushi/v5--Teo--Palmar_Chico--mushi_demography.txt"

def build_demography(demography_file):
    en_string = ""
    with open(demography_file) as f:
        t, N, pop = f.readline().strip().split()
        N0 = float(N)
        for line in f:
            t, N, pop = line.strip().split()
            t_scaled = float(t) / (4*N0)
            N_scaled = float(N) / N0
            en_string += f"-en {t_scaled:0.6f} 0 {N_scaled:0.6f} "
    return {"en": en_string, "N0": N0}
            
demog_dict = build_demography(demography_file)

print(f"discoal {nsamp}")
